
name: CI Selenium

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"                 # Habilita caché integrado de pip para acelerar

      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # (Opcional) Instalar Chromium si tu runner lo necesita
      # - name: Instalar Chromium
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y chromium-browser

      - name: Ejecutar script de Selenium
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          python integracion.py
